# Generated by Django 2.0.9 on 2018-11-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181114_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='cliente',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
