# Generated by Django 2.0.9 on 2018-11-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181114_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cliente',
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
